title: mandoobox
description: zzim-tong
url: "https://mandoobox.github.io/"
baseurl: ""
lang: ko
timezone: Asia/Seoul

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .next/
  - posts/
